services:
  horsemart:
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - .:/HorseMart
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"


